version: "3"

services:
  database:
    image: postgres:12.3
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: starwars

  adminer:
    image: adminer:4.7.7
    depends_on:
      - database
    ports:
      - "8090:8080"
    expose:
      - "8090"
