# Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/starwars}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driverClassName: ${DB_DRIVERCLASSNAME:org.postgresql.Driver}

  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

    # Hibernate ddl auto
    hibernate:
      ddl-auto: create-drop


# Properties of application
problem2:
  start-wars-api-url: ${START_WARS_API_URL:https://swapi.py4e.com/api/}
